import type { CSSProperties } from "react";
import type { FrettedInstrumentVoicing } from "achorde-musical-domain";
import type { FretboardHandedness, FretboardOrientation } from "../../layout/types.js";
import type { InteractiveFretboardChangeDetails } from "../../adapters/applyChangePipeline.js";

export type InteractiveFretboardProps = {
	value?: FrettedInstrumentVoicing;
	valueMode?: "voicing" | "fretNotation";
	fretNotation?: string;
	chordSymbol?: string;
	onChange?: (details: InteractiveFretboardChangeDetails) => void;
	orientation?: FretboardOrientation;
	handedness?: FretboardHandedness;
	fretCount?: number;
	stringCount?: number;
	tuning?: string[];
	inferBarresOnChange?: boolean;
	detectChord?: boolean;
	showFretNumbers?: boolean;
	showInlays?: boolean;
	showDotText?: boolean;
	showTuning?: boolean;
	viewBoxWidth?: number;
	viewBoxHeight?: number;
	minHitSize?: number;
	className?: string;
	style?: CSSProperties;
	disabled?: boolean;
	"aria-label"?: string;
};
